name: Pharalert
description: "tugas UAS."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  intl: ^0.17.0 
  
  curved_navigation_bar: ^1.0.3
  curved_labeled_navigation_bar: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  shared_preferences: ^2.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  family: Schyler
  fonts:
    - asset: assets\fonts\PoppinsRegular.ttf
    - asset: assets\fonts\PoppinsSemiBold.ttf